url: http://crumbsandcrumbles.eu
baseurl: 

# Site settings
title: Crumbs & Crumbles
logo: logo.png
slogan: In Love with Cake
email: liana@crumbsandcrumbles.eu
phone: "+356 9984 2600"
description: Home baked cakes for you!
# season: Strawberries
# seasonMessage: Let's start strawberry picking!!
# seasonBackground: strawberries-background.jpg
# tickerMessage: Christmas is approaching. I am already working on my homemade mince. The secret is preparing it early so it has plenty of time to infuse and become delicious. That is why there will be limited availability. If you're interested in having some of my delicious Mince Pies or Xmas Cake in time for the festivities, please place your order as soon as possible :)
# tickerBackground: Seasonal/Christmas/santa.png

# Customers
people:
- name: Amber
  pic: amber.png
  review: "You never fail to impress! Cakes taste and look amazing. Thanks Liana!"
- name: Ludwig
  pic: ludwig.png
  review: "That was the best birthday cake I ever had! Awesome!"
- name: Rahul
  pic: rahul.png
  review: "Rainbow cake was really delecious. Entire family loved it! Thank you Liana."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/crumbsandcrumblesmalta/
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Serve to everyone
host: 0.0.0.0

# Plugin section
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap  

# Locale
lang: en_UK